name: CI

on:
  push:
    branches: [main, dev, dev-nextjs-mdx]
  pull_request:
    branches: [main, dev, dev-nextjs-mdx]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install dependencies
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#yarn
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./build

  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

